name: CI Tests with Allure

on: [push, pull_request]

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Start containers (MySQL)
        run: |
          docker compose up -d 
          sleep 10  # Wait for DB initialization

      - name: Run SUT (MySQL)
        run: |
          java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app \
               -jar artifacts/aqa-shop.jar &
          sleep 15  # Wait for app startup

      - name: Run tests (MySQL)
        run: |
          ./gradlew clean test \
            -Ddb.url=jdbc:mysql://localhost:3306/app \
            -Dselenide.headless=true \
            --info

  test-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start containers (PostgreSQL)
        run: |
          docker compose up -d 
          sleep 10  # Wait for DB initialization

      - name: Run SUT (PostgreSQL)
        run: |
          java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app \
               -jar artifacts/aqa-shop.jar &
          sleep 15  # Wait for app startup

      - name: Run tests (PostgreSQL)
        id: tests
        run: |
          ./gradlew clean test \
            -Ddb.url=jdbc:postgresql://localhost:5432/app \
            -Dselenide.headless=true \
            --info

      - name: List Allure results
        if: always()
        run: ls -l allure-results || echo "No results found"

      - name: Install Allure CLI
        if: always()
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate build/allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 5

      - name: Show Allure result files content
        if: always()
        run: |
          for f in build/allure-results/*-result.json; do
            echo "===== $f ====="
            cat "$f"
            echo
          done

      - name: Deploy to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report